### ISSUE TITLE
Hi, I wanna join as a contributor in refactoring 

### ISSUE THREAD

**Issue by bettdouglas** [Gubaer/dart-simple-features#1]
Is there any way we can work together to do this. I've gone through your code and the avl tree but a lot of errors come up since I started learning dart last year but I'm really loving it. 
Since dart is also an being uptaken by developers alot, we can help the OpenGeo community.
this code to update it to the latest dart version and if you could help, I could maintain the code after understanding it well.

**Comment by Gubaer** [comment]
Hi, I worked on this repo two or three years ago. Unfortunately, I didn't have enough spare time to continue the work. You probably already noticed that this is very much work in progress. Your help would be welcome! It would be great, if the code turned into something useful for the OpenGeo community.

**Comment by bettdouglas** [comment]
Since dart_jts has been created, i bet i I can close this
